app_name: ModelsHost
env: dev
port: 57820

telegram:
  token: 344617953:AAECfdvjZEZjSQk4GAfBAT0BlMElXUs2Tn4
  chat_id: 211945135

log:
  level: 20  #ERROR = 40 | WARNING = 30 | INFO = 20 | DEBUG = 10
  path: ./logs/

models:
  v8.Basic-1.1:
    gen: gen8
    period: 300
    disabled: False
    path: models/model_gen8-Basic-1.1

  v8.FutureFeature-2.1:
    gen: gen8
    period: 300
    disabled: False
    path: models/model_gen8-FutureFeature-2.1

