app_name: ModelsHost
env: dev
port: 57820

telegram:
  token: 344617953:AAECfdvjZEZjSQk4GAfBAT0BlMElXUs2Tn4
  chat_id: 211945135

log:
  level: 20  #ERROR = 40 | WARNING = 30 | INFO = 20 | DEBUG = 10
  path: ./logs/

models:
  v7.4_basic:
    gen: gen7
    period: 300
    disabled: False
    path: models/model_app-test-8.2.1-FutureFeature

  v7.4_spread:
    gen: gen7
    period: 300
    disabled: False
    path: models/model_app-test-8.2.1-FutureFeature

  v8.2.1-FutureFeature:
    gen: gen8
    period: 900
    disabled: False
    path: models/model_app-test-8.2.1-FutureFeature
    info: Модель с максимальным результатом на тестовых данных