app_name: ModelsHost
env: dev
port: 57820

telegram:
  token: 344617953:AAECfdvjZEZjSQk4GAfBAT0BlMElXUs2Tn4
  chat_id: 211945135

log:
  level: 20  #ERROR = 40 | WARNING = 30 | INFO = 20 | DEBUG = 10
  path: ./logs/

models:
  v7.4_basic:
    gen: gen7
    timerate: 5min
    disabled: False
    model_path: models/model_app-test-8.2.1-FutureFeature
    info: /gen7/5m/v7.4_basic

  v7.4_spread:
    gen: gen7
    timerate: 5min
    disabled: False
    model_path: models/model_app-test-8.2.1-FutureFeature
    info: /gen7/5m/v7.4_basic

  v8.2.1-FutureFeature:
    gen: gen8
    timerate: 15min
    disabled: False
    model_path: models/model_app-test-8.2.1-FutureFeature
    path: /gen8/15min/v8.2_basic
    info: Модель с макскимальным результатом на тестовых данных